version: '3.8'

services:
  llm_router:
    build: .
    container_name: llm_router_service
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python src/router.py
